import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/components/Auth/UserContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { MissionProvider } from "@/contexts/MissionContext";
import { Router } from "react-router-dom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
      <MissionProvider>
     <Router>

      
        <UserProvider>{children}</UserProvider>
        </Router>
         </MissionProvider>
    </AuthProvider>
        
      </body>
    </html>
  );
}
